### ISSUE TITLE
Wrong upgrades for other mods' loaders

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [kirazy/vanilla-loaders-hd#3]
Hello again.
I was testing new loaders and found an interesting bug.
![Screenshot 1](https://i.imgur.com/WecfJgl.png)
![Screenshot 2](https://i.imgur.com/cLfdjNi.png)
[Mod (RandomFactorioThings) source](https://github.com/JohnTheCoolingFan/RandomFactorioThings/tree/dev)

**Comment by kirazy** [comment]
What's your mod combinations right now? Upgrade paths work fine for me. X:

**Comment by kirazy** [comment]
Okay so there's an oversight in my function in that I don't have a provision to set an upgrade target. Lemme add that.

**Comment by kirazy** [comment]
Commit 4251903258f64d67b0ee47a66a74909c5aee8df4 should resolve #3.

In the function you can specify a next_tier as an optional parameter:
`vanillaHD.addLoader(name, color, belt_name, technology, previous_tier, next_tier)`

**Comment by JohnTheCoolingFan** [comment]
Ok, I tested it and it works perfectly. Thanks.

**Comment by kirazy** [comment]
Actually, I'm thinking about this and I'm not sure this is actually fixed.

The current method is circular, e.g. if you try to define your Plutonium loader, it assumes the nuclear loader exists and tries to set it as the previous tier. But the Nuclear loader can't be created until the Plutonium loader is, because it needs to set it as an upgrade target.

So I think I need to break the upgrade path method into its own separate function that you can call after you've setup the loaders.

**Comment by kirazy** [comment]
Okay it's fine, just need to clarify how next_tier should be used. If you're adding multiple loaders, because the function will go back and edit the upgrade path in the previous tier to point to the one being created, there's no need to specify next tier ever, unless you're adding a loader in between other loaders...
